# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 465663191c1a3387ac017871694a0ace2f32f99eb8d35f8448a1771ef7b9623783dd0e92a5d336d25263b6f1e8a14d2537b56c6183156effc3d72e324606525c

test:
  secret_key_base: 369f7d2b9d2d0af2f33208c3a683ea75f1fb548047314a7d012dccb20b2ed931058c8e4466d9ccb6201a62cb1a67fe0924869caf871f0fa6df39c3de9b07a346

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
